### PR TITLE
add dbDriver allow to override for pyodbc

### PR DESCRIPTION
**Pull request by IlfirinPL**
#134  @jerry57

Code with added support

### CODE REVIEW

**Comment by jerry57** [comment]
You appear to be missing a comma on line 37 after "dbDriver=None".  Could you also add testcases/suite to show that this is working please.

**Comment by IlfirinPL** [comment]
Yes, I will

**Comment by IlfirinPL** [comment]
Test Added

**Comment by jerry57** [comment]
I have merged into master for now.  Will be part of next release

**Pull request merged**
