### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by tisto**
Also added Travis CI configuration to test Postgres, SQLite and MySQL.

### CODE REVIEW

**Comment by tisto** [comment]
@jerry57 would you mind having a look at this pull request? Let me know if there is anything missing.

**Comment by jerry57** [comment]
Sorry, have not had a chance to review this yet, crazy week.  Will try 
to look at it by weeks end though.

Jerry S

On 6/9/16 12:29 AM, Timo Stollenwerk wrote:
>
> @jerry57 <https://github.com/jerry57> would you mind having a look at 
> this pull request? Let me know if there is anything missing.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/franz-see/Robotframework-Database-Library/pull/60#issuecomment-224820061>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AAm11nJcC5LzjaErAVauN7fvoLXMZPwiks5qJ8DzgaJpZM4Irlgk>.
>

-- 
Linux registered user #475536
Ubuntu registered user #28583

**Comment by tisto** [comment]
@jerry57 thanks for merging! Any chance to get a new Python 3 compatible release?

**Comment by jerry57** [comment]
I have not specifically tested that, but looks like it should be. That 
is why I didn't include it in the announcement.

jer

On 6/13/16 12:24 PM, Timo Stollenwerk wrote:
>
> @jerry57 <https://github.com/jerry57> thanks for merging! Any chance 
> to get a new Python 3 compatible release?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/franz-see/Robotframework-Database-Library/pull/60#issuecomment-225681903>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AAm11sHN5c8FrAMPYV0N2HM5DoOq4lHdks5qLa56gaJpZM4Irlgk>.
>

-- 
Linux registered user #475536
Ubuntu registered user #28583

**Pull request merged**
